### ISSUE TITLE
Launches App doesn't fit last Item properly

### ISSUE THREAD

**Issue by kruux** [sebastiangelotte/rymdklubben#3]
## Expected behavior
Last Item should fit correctly, as well as the scrollbar.

## Actual behavior
Instead half the scrollbar and the bottom part of the Item dissapear under the bottom of the browser.

## Steps to reproduce the behavior
Start the dev server and browse to launches. Then scroll to the bottom.
Similar behaviour on both firefox and chrome.

**Comment by kruux** [comment]
I believe the cause might be because of an incorrect, or lack of height value somewhere. Most likely a css issue anyway.

**Comment by sebastiangelotte** [comment]
What do you think about #4 as a solution?
